spring:
  application:
    name: index-data-service
#  redis:
#    password: 123456

server:
  port: 8021

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: 192.168.1.6