server:
  port: 8041

spring:
  application:
    name: trend-trading-backtest-view
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: 192.168.1.6